### ISSUE TITLE
# Number Guessing Game Issue

### ISSUE THREAD

**Issue by ImBoaHancock** [ImBoaHancock/SecondRepo#11]
## Issue: Add JavaScript Logic for Guessing

The current `number-guess.html` file is missing the main functionality for the number guessing game. Here's what needs to be done:

### Tasks:
- **Generate Random Number**: Write a function that generates a random number between 1 and 100.
- **Capture User Input**: Get the user's guess from the input field when the "Submit Guess" button is clicked.
- **Compare Guess**: Compare the user's guess with the random number and provide feedback.
  - Display “Too high!” if the guess is greater than the random number.
  - Display “Too low!” if the guess is less than the random number.
  - Display “Correct!” if the guess matches the random number.

Once completed, the game should allow users to make guesses and get feedback based on their inputs.

**Comment by SubediBinod** [comment]
assign me
