### ISSUE TITLE
# Random Quote Generator Issues

### ISSUE THREAD

**Issue by ImBoaHancock** [ImBoaHancock/SecondRepo#5]
# Random Quote Generator Issues
## Issue: Add Basic Features to the Random Quote Generator

The current `random-quote.html` file has minimal functionality. Here's what needs to be done to complete the file:

### Tasks:
- **Add Quotes Array**: Populate the JavaScript `quotes` array with 5-10 quotes.

**Comment by SubediBinod** [comment]
assign me
