### ISSUE TITLE
 Random Quote Generator Issues

### ISSUE THREAD

**Issue by ImBoaHancock** [ImBoaHancock/SecondRepo#7]
# Random Quote Generator Issues

## Issue: Add Basic Features to the Random Quote Generator

The current html file has minimal functionality. Here's what needs to be done to complete the file:

### Tasks:
- **Implement Random Quote Display**: Write a JavaScript function that displays a random quote from the array when the "New Quote" button is clicked.

**Comment by SubediBinod** [comment]
assign me
